services:
  - type: web
    name: Georges
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HOST
        sync: false
      - key: PORT
        sync: false
